services:

  mariadb:
    container_name: mariadb_ctr
    build: 
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: example.env
    restart: unless-stopped
    networks:
      - inception
    expose:
      - 3306
    #volumes:
      #- mariadb_data:/var/lib/mysql

  nginx:
    container_name: nginx_ctr
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: example.env
    depends_on:
      - wordpress
    restart: unless-stopped
    networks:
      - inception
    ports:
      - "443:443"

  wordpress:
    container_name: wordpress_ctr
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file: example.env
    depends_on:
      - mariadb
    restart: unless-stopped
    networks:
      - inception
    expose:
      - 9000
    #volumes:
      #- wordpress_data:/var/www/html

networks:
  inception:
    driver: bridge