name: inception

services:
  mariadb:
    image: mariadb
    container_name: mariadb_ctr
    build: 
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: example.env
    restart: unless-stopped
    networks:
      - inception_net
    expose:
      - 3306
    volumes:
      - mariadb_data:/var/lib/mysql
  nginx:
    image: nginx
    container_name: nginx_ctr
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: example.env
    depends_on:
      - wordpress
    restart: unless-stopped
    networks:
      - inception_net
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/wordpress
  wordpress:
    image: wordpress
    container_name: wordpress_ctr
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file: example.env
    depends_on:
      - mariadb
    restart: unless-stopped
    networks:
      - inception_net
    expose:
      - 9000
    volumes:
      - wordpress_data:/var/www/wordpress

networks:
  inception_net:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/mbecker/data/mariadb_data
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/mbecker/data/wordpress_data
      o: bind
